podman: enforce runtime=runc (#972)
With the default crun runtime of podman, "osc build" fails because the
--mount option with destination=/ doesn't seem to be supported:

   Error: OCI runtime error: crun: mount `/mnt/git/build-root/15.5-x86_64/.mount` to ``: Invalid argument

fcrozat told me on Slack that setting runc as runtime works, and
indeed it does. But if build depends on this, it should rather set
this runtime explitly.

Signed-off-by: Martin Wilck <mwilck@suse.com>