untested fix for crazy GNU "chroot /" behavior
see http://marc.info/?t=140655718900007&r=1&w=2

arch broke with the attempt to teach it preinstall images:

  init_buildsystem --configdir /.build/configs --cachedir /var/cache/build /.build-srcdir/PKGBUILD build rpmlint-Factory ...
  [1/91] installing archlinux-keyring
  error: '.init_b_cache/archlinux-keyring.arch': could not find or read package
  [2/91] installing iana-etc
  error: '.init_b_cache/iana-etc.arch': could not find or read package
  ...

according to [0], it might be a GNU chroot(1) bug[1]

[0] http://marc.info/?l=opensuse-buildservice&m=140655932513048&w=2
[1] http://bugs.gnu.org/18062